### ISSUE TITLE
Panic occurs when touching the touchpad with libinput v1.19.

### ISSUE THREAD

**Issue by yskszk63** [Smithay/input.rs#31]
When I run this example described in the README in my environment, I get a panic.
It happens when touch the touchpad.

```rust
use std::fs::{File, OpenOptions};
use std::os::unix::{fs::OpenOptionsExt, io::{RawFd, FromRawFd, IntoRawFd}};
use std::path::Path;

use input::{Libinput, LibinputInterface};
use libc::{O_RDONLY, O_RDWR, O_WRONLY};

struct Interface;

impl LibinputInterface for Interface {
    fn open_restricted(&mut self, path: &Path, flags: i32) -> Result<RawFd, i32> {
        OpenOptions::new()
            .custom_flags(flags)
            .read((flags & O_RDONLY != 0) | (flags & O_RDWR != 0))
            .write((flags & O_WRONLY != 0) | (flags & O_RDWR != 0))
            .open(path)
            .map(|file| file.into_raw_fd())
            .map_err(|err| err.raw_os_error().unwrap())
    }
    fn close_restricted(&mut self, fd: RawFd) {
        unsafe {
            File::from_raw_fd(fd);
        }
    }
}

fn main() {
    let mut input = Libinput::new_with_udev(Interface);
    input.udev_assign_seat("seat0").unwrap();
    loop {
        input.dispatch().unwrap();
        for event in &mut input {
            println!("Got event: {:?}", event);
        }
    }
}
```

Output

```bash
$ cargo run
Got event: Device(Added($struct_name @0x55f840b399f0))
Got event: Device(Added($struct_name @0x55f840b40550))
Got event: Device(Added($struct_name @0x55f840b646d0))
Got event: Device(Added($struct_name @0x55f840b6a3c0))
Got event: Device(Added($struct_name @0x55f840b700c0))
Got event: Device(Added($struct_name @0x55f840b802d0))
Got event: Device(Added($struct_name @0x55f840b853f0))
Got event: Device(Added($struct_name @0x55f840b8e330))
Got event: Device(Added($struct_name @0x55f840b95980))
Got event: Device(Added($struct_name @0x55f840b9c730))
Got event: Pointer(Motion($struct_name @0x55f840b53640))
thread 'main' panicked at 'libinput returned invalid 'libinput_event_type'', /home/ysk/.cargo/registry/src/github.com-1ecc6299db9ec823/input-0.6.0/src/event.rs:108:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My Environemnt

```bash
$ cat /etc/os-release|grep -e^NAME
NAME="Arch Linux"
$ pacman -Q libinput
libinput 1.19.0-1
$ cargo build -v|&grep -e' input'
       Fresh input-sys v1.15.1
       Fresh input v0.6.0
```

It seems that the following event types have been [added](https://github.com/wayland-project/libinput/commit/b6b15fa30467c639983da0e22298913d6058b702#diff-4d73b776d4a1f242629bfa96dbccac16dcaa77945d57878ed2608aba2d261c46) in libinput v1.19.

- `LIBINPUT_EVENT_GESTURE_HOLD_BEGIN`
- `LIBINPUT_EVENT_GESTURE_HOLD_END`

**Comment by Drakulix** [comment]
Can you additionally please provide a backtrace?
`env RUST_BACKTRACE=1 cargo run`

I will try to get to this soonish, adding those new events should be rather straight-forward.

**Comment by yskszk63** [comment]
> Can you additionally please provide a backtrace?
> `env RUST_BACKTRACE=1 cargo run`

I added a back trace.

```
thread 'main' panicked at 'libinput returned invalid 'libinput_event_type'', /home/ysk/.cargo/registry/src/github.com-1ecc6299db9ec823/input-0.6.0/src/event.rs:108:18
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:541:12
   1: <input::event::Event as input::FromRaw<input_sys::libinput_event>>::from_raw
             at /home/ysk/.cargo/registry/src/github.com-1ecc6299db9ec823/input-0.6.0/src/event.rs:108:18
   2: <input::context::Libinput as core::iter::traits::iterator::Iterator>::next
             at /home/ysk/.cargo/registry/src/github.com-1ecc6299db9ec823/input-0.6.0/src/context.rs:141:27
   3: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/iter/traits/iterator.rs:3477:9
   4: libinput_test::main
             at ./src/main.rs:32:22
   5: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Thank you for your quick reply.

**Comment by Drakulix** [comment]
Can you please try #32 and see if that fixes your error?

Once with the default feature set, which should enable all the new stuff of libinput 1.19 (high-resolution scrolling and hold gestures) and once without the "libinput_1_19" feature to test, that it does not crash anymore?

I have also tried to make input.rs more resilient to libinput changes in the future, so that new versions hopefully do not cause crashes anymore, if they introduce new event types.

**Comment by yskszk63** [comment]
I tried #32, but got a different error..

```bash
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/libinput-test`
Got event: Device(Added($struct_name @0x55935799c9f0))
Got event: Device(Added($struct_name @0x5593579a3550))
Got event: Device(Added($struct_name @0x5593579c76d0))
Got event: Device(Added($struct_name @0x5593579cd3c0))
Got event: Device(Added($struct_name @0x5593579d30c0))
Got event: Device(Added($struct_name @0x5593579e32d0))
Got event: Device(Added($struct_name @0x5593579e83f0))
Got event: Device(Added($struct_name @0x5593579f1330))
Got event: Device(Added($struct_name @0x5593579f8980))
Got event: Device(Added($struct_name @0x5593579ff730))
libinput error: client bug: Invalid event type LIBINPUT_EVENT_GESTURE_HOLD_BEGIN (806) passed to libinput_event_gesture_get_base_event()
zsh: segmentation fault (core dumped)  RUST_BACKTRACE=1 cargo run
```

The error that occurs is the same regardless of whether `libinput_1_19` feature is present or not.

The dependencies of Cargo.toml are as follows.

```toml
...
[dependencies.input]
git = "https://github.com/Smithay/input.rs"
rev = "9f019d130e727bd6e18889189bb3a31cd5bd16cd"
features = [
    "libinput_1_19",
]
```

**Comment by Drakulix** [comment]
Thanks for trying, I did not have the time to setup a test system with libinput 1.19 yesterday, so I assumed there would likely be an error left, but this is not what I expected.

From looking at this source, this appears to be a libinput bug, rather then a input-rs bug, so I have reported that issue upstream: https://gitlab.freedesktop.org/libinput/libinput/-/issues/671

I see no *easy* way to fix this in input-rs without some restructuring, so I hope this can be quickly addressed upstream instead.
If not I will try come up with a workaround.

**Comment by Drakulix** [comment]
https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/697/

^ Seems to solved upstream soon

**Comment by yskszk63** [comment]
> https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/697/

It seems to be merged.
Using the main branch of libinput seems to be working fine.

```
$ docker run --rm --device /dev/input --mount type=bind,source=/run/udev,target=/run/udev,readonly ghcr.io/yskszk63/inputrs-with-gesture-hold:main /app
Got event: Device(Added($struct_name @0x55a56d0ea930))
Got event: Device(Added($struct_name @0x55a56d0f0fd0))
Got event: Device(Added($struct_name @0x55a56d112e50))
Got event: Device(Added($struct_name @0x55a56d118480))
Got event: Device(Added($struct_name @0x55a56d11dab0))
Got event: Device(Added($struct_name @0x55a56d12d9a0))
Got event: Device(Added($struct_name @0x55a56d130fa0))
Got event: Device(Added($struct_name @0x55a56d13ba70))
Got event: Device(Added($struct_name @0x55a56d141cb0))
Got event: Device(Added($struct_name @0x55a56d147fb0))
Got event: Gesture(Hold(Begin($struct_name @0x55a56d105d80)))
Got event: Pointer(Motion($struct_name @0x55a56d0f5890))
Got event: Pointer(Motion($struct_name @0x55a56d0f5890))
Got event: Pointer(Motion($struct_name @0x55a56d0f5890))
Got event: Pointer(Motion($struct_name @0x55a56d0f5890))
Got event: Gesture(Hold(End($struct_name @0x55a56d105d80)))
Got event: Keyboard(Key($struct_name @0x55a56d0c3e10))
Got event: Keyboard(Key($struct_name @0x55a56d0c3e10))
...
```

This is the Docker image used for verification.
https://github.com/yskszk63/inputrs-with-gesture-hold

**Comment by Drakulix** [comment]
0.7.0 with libinput 1.19 support is published on crates.io

**Comment by yskszk63** [comment]
Thank you.
I appreciate your fantastic job!
